# Generated by Django 4.0 on 2022-05-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_categoria_alter_producto_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
