# Generated by Django 4.0 on 2022-05-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='urlImagen',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
