# Generated by Django 4.0 on 2022-05-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_producto_urlimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='urlImagen',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
