# Generated by Django 4.0 on 2022-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_producto_urlimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folioVenta', models.IntegerField()),
                ('articulo', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('apellidoCliente', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Domicilio', models.CharField(max_length=150)),
                ('infoAdicional', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('codigoPostal', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('total', models.FloatField()),
                ('idCliente', models.IntegerField()),
                ('formaPago', models.CharField(max_length=30)),
                ('nombrePropietario', models.CharField(max_length=100)),
                ('numeroTarjeta', models.CharField(max_length=16)),
                ('vencimiento', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
