# Generated by Django 4.0 on 2022-05-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_articulovendido_cliente_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='folio',
        ),
    ]
