# Generated by Django 4.0 on 2022-05-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_venta_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fechaRealizada',
            field=models.DateField(null=True),
        ),
    ]
